### ISSUE TITLE
Error „Texture.js: 1054 WebGL: INVALID_VALUE: texImage3D: width, height or depth out of range”

### ISSUE THREAD

**Issue by arminwegner** [cornerstonejs/cornerstone3D-beta#119]
When I try to display a DR image (size 4048x4932) a get the error message ‘Texture.js: 1054 WebGL: INVALID_VALUE: texImage3D: width, height or depth out of range’. I guess this is due to the webgl limit: ‘MAX_3D_TEXTURE_SIZE’, which is 2048 on my system (chrome). Does this mean that it is not possible to display simple DR images with one dimension larger than 2048? Unfortunately, we have many of them. Is it necessary to use a 3D texture for plain DR images?

**Comment by swederik** [comment]
We don't currently have any fallback to 2D textures at the moment, but you should be able to fallback to CPU rendering instead of using the GPU. 

What does https://webglreport.com/ give you?

**Comment by swederik** [comment]
Completely agree, I don't know how we didn't hit this issue before... we are looking into it!

**Comment by swederik** [comment]
We are working on switching to 2D textures for stack viewports (e.g. when the image dimensions are too big for a 3D texture) here: https://github.com/cornerstonejs/cornerstone3D-beta/pull/127

**Comment by swederik** [comment]
Should be fixed now if you want to try again. Note that you can't do 3D volumes that large, but you should be able to do 2D images that large without an issue.
