### ISSUE TITLE
Support for fully custom viewports not yet implemented

### ISSUE THREAD

**Issue by zhoualibaba** [cornerstonejs/cornerstone3D-beta#124]
When i run example locally,i got many error like this
![image](https://user-images.githubusercontent.com/17982206/172793788-0c4c4874-c511-40d9-aac5-82fdb002d685.png)
I wonder if this is my fault.
I got the same error when i run the example "https://www.cornerstonejs.org/docs/tutorials/basic-segmentation-tools".

**Comment by songhao5518** [comment]
Hello, this problem occurred when I ran this example(https://www.cornerstonejs.org/docs/tutorials/basic-volume). Have you encountered it?
![image](https://user-images.githubusercontent.com/72715899/177991303-d51c34f3-d1d5-4be0-8b44-11f799438fa8.png)

**Comment by zhoualibaba** [comment]
resolved

**Comment by MYWpro** [comment]
> resolved

How did you solve it?
