### ISSUE TITLE
CornerStone3D-beta library can't render X-Ray images(CR, DX, XO, e.g,) 

### ISSUE THREAD

**Issue by Vladimir-Kharam** [cornerstonejs/cornerstone3D-beta#137]
We have application  based on CornerStone3D-beta library. The application can work properly with CT, PT images.
 The applications can't display images  For X-Ray images(CR, DX, XO,)
 The question is following:  Can CornerStone3D-beta library render and display X-Ray Images ?

If answer is positive can you give us the link of working code to display X-Ray images(CR, DX, XO) CornerStone3D- library.

Thanks in advance

**Comment by swederik** [comment]
That should work now, we improved the 2D image support recently. Are you using the latest version?

**Comment by swederik** [comment]
Can you post an example image? What kind of errors are you getting? Large images seem to be working fine for me, so maybe this is another issue.

**Comment by Vladimir-Kharam** [comment]
Thanks for the response.

We don't have errors in rendering, but viewport is not displayed 

I am attaching the anonymized file with modality "CR"  

[cr2022.zip](https://github.com/cornerstonejs/cornerstone3D-beta/files/8977037/cr2022.zip)

**Comment by Vladimir-Kharam** [comment]
Thanks a lot.
