### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createAndCacheVolume')

### ISSUE THREAD

**Issue by songhao5518** [cornerstonejs/cornerstone3D-beta#145]
Hello, this problem occurred when I ran this example(https://www.cornerstonejs.org/docs/tutorials/basic-volume). Have you encountered it?
![image](https://user-images.githubusercontent.com/72715899/178142165-b76fe119-7048-41da-a9a7-86572b6db8e1.png)

**Comment by sedghi** [comment]
How did you run it?

**Comment by songhao5518** [comment]
I have solved this problem. Thank you for your reply.

**Comment by sedghi** [comment]
@songhao5518 Can you post your solution here for others as well? Thanks

**Comment by songhao5518** [comment]
I use the react framework. When using some functions, cross source isolation will occur. Add the setupproxy.js file in the SRC directory. The file content is:

module. exports = function(app){

app. use((req,res,next) => {

res.setHeader('Cross-Origin-Embedder-Policy','require-corp')

res.setHeader('Cross-Origin-Opener-Policy','same-origin')

next()

})

}
