### ISSUE TITLE
Examples break when using streaming-wadors

### ISSUE THREAD

**Issue by heyflynn** [cornerstonejs/cornerstone3D-beta#149]
I ran into an issue while doing the examples and trying to use steaming-wadors

in all the Volume examples, imageIds are created and cached with the  createImageIdsAndCacheMetaData helper function and 'VOLUME' (upper case string) for type.
https://github.com/cornerstonejs/cornerstone3D-beta/blob/659888db44ab70d562f7f52872c822feb5c1db03/packages/core/examples/multiVolumeAPI/index.ts#L214

After closer inspection of the helper function you, which prefix is determined here

https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/utils/demo/helpers/createImageIdsAndCacheMetaData.js#L51

but VOLUME constant is  
`const VOLUME = 'volume';`

When I fix the constant to 'VOLUME' the streaming loader fails to initialize with the following exception... "Error: cornerstoneWADOImageLoader requires a copy of Cornerstone to work properly."
![image](https://user-images.githubusercontent.com/553465/179530951-f5d8586e-2c7b-4d4d-919e-edc4dd142545.png)

**Comment by sedghi** [comment]
Hmmm, so was it working with the `VOLUME` as type you are saying? As the error says you need to pass in the cornerstone to the cornerstoneWADOImageLoader, similar to what we do [here](https://github.com/cornerstonejs/cornerstone3D-beta/blob/a0eefdc34e171ac35375fe58c5da75575ed6d46e/utils/demo/helpers/initCornerstoneWADOImageLoader.js#L6)

**Comment by heyflynn** [comment]
what I mean is that the examples don't ever use streaming-image-volume-loader.

in the all the volume examples, the function createImageIdsAndCacheMetaData is called with an upper case string 'VOLUME'

in the examples createImageIdsAndCacheMetaData is called with type parameter as 'VOLUME' (upper case string ) that is evaluated against the constant VOLUME which is 'volume' (lower case).

`const prefix = type === VOLUME ? 'streaming-wadors:' : 'wadors:';`

will always be set to 'wadors:'

if I set the createImageIdsAndCacheMetaData to 'volume' then it tries to load images using streaming-wadors.

that's when streaming-image-volume-loader fails with the exception provided above.

I do have cornerstone external initialized properly as you pointed out.

**Comment by sedghi** [comment]
I see, yeah this is a bug, but changing the it to `volume` doesn't give me error. 

Basically the difference between `wadors` and `streaming-wadors` image loaders is that `wadors` creates the image object, but in the `streaming-wadors` which uses [SharedArrayBufferImageLoader](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/streaming-image-volume-loader/src/sharedArrayBufferImageLoader.ts), it basically goes through the same process just don't create the image object (optimization for speed, since images are _inserted_ into the volume and we don't need the image object basically).

So this subtle bug was creating the image objects but the pixeldata was also inserted into the volume. 

How do you run the example that you get the error? Maybe check this out https://www.cornerstonejs.org/docs/tutorials/examples

![image](https://user-images.githubusercontent.com/7490180/183977684-38f5f3fa-2d5f-4a0d-aca2-170d7421a325.png)

**Comment by heyflynn** [comment]
thanks for looking into it, the problem is with my code then. 

I'm using Create React App and I don't think webpack is linking the same cornerstone-wado-image-loader module.

example: sharedArrayBufferImageLoader uses this dynamic import instead of the alias.

https://github.com/cornerstonejs/cornerstone3D-beta/blob/105bd9d97e0df6e67a61c5e13b3393a106ff69d5/packages/streaming-image-volume-loader/src/sharedArrayBufferImageLoader.ts#L7
`'cornerstone-wado-image-loader/dist/dynamic-import/cornerstoneWADOImageLoader.min.js';`

I tried making an alias for this module but that fails with a different error.

**Comment by sedghi** [comment]
Thanks for reporting this bug, now our examples are much faster haha

I expect that the error don't happen if you don't link anything, right? Look into the OHIF webpack (which is basically ejected version of CRA), to see how we are setting the aliases etc.

**Comment by heyflynn** [comment]
fantastic!

I missed the part about dynamic-imports from cornerstoneWadoImageLoader for upgrading to 4.0. Adding the alias for dynamic imports and adding CopyWebpackPlugin to copy to the build folder solved my last issue. 

My examples are working using streaming-wadors now.

Thanks for your help.

**Comment by selimcanglr** [comment]
I currently have the same issue. I've also created my React app with 'create-react-app' and get the same error message. Do you mind sharing how did you add the alias and the CopyWebpackPlugin?

**Comment by yanqzsu** [comment]
> I currently have the same issue. I've also created my React app with 'create-react-app' and get the same error message. Do you mind sharing how did you add the alias and the CopyWebpackPlugin?
You can refer to [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader#upgrade-to-cwil-v4x)

**Comment by selimcanglr** [comment]
> You can refer to [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader#upgrade-to-cwil-v4x)
> > I currently have the same issue. I've also created my React app with 'create-react-app' and get the same error message. Do you mind sharing how did you add the alias and the CopyWebpackPlugin?
> 
> 
> 

I have already solved the problem on my side. However, CopyWebpackPlugin part in the upgrade guide is outdated and not working anymore as it is. I have created a pull request to fix it.

**Comment by heyflynn** [comment]
> > You can refer to [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader#upgrade-to-cwil-v4x)
> > > I currently have the same issue. I've also created my React app with 'create-react-app' and get the same error message. Do you mind sharing how did you add the alias and the CopyWebpackPlugin?
> 
> I have already solved the problem on my side. However, CopyWebpackPlugin part in the upgrade guide is outdated and not working anymore as it is. I have created a pull request to fix it.

Are you still having a problem with this?

if so, I can create a bootstrap for Create React App and Cornerstone 3D.
