### ISSUE TITLE
local load  ww/wc viewport  display is not accurate

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D-beta#153]
![0a79d63eb23621e4cd405dc1b445626](https://user-images.githubusercontent.com/41686843/181210800-efd7febb-d888-4d7a-ad50-d6582e63c04c.jpg)

i think the image display is not accurate
 
![d07be611f947ddc036de9e10f6ed937](https://user-images.githubusercontent.com/41686843/181211186-04964325-c534-48d3-a8ae-541916775df5.jpg)

Here's the old version,the picture above is an example of the new version

**Comment by tineke01** [comment]
[1.3.12.2.1107.5.1.4.66005.30000017050400361916400003811 (3).dcm.zip](https://github.com/cornerstonejs/cornerstone3D-beta/files/9210408/1.3.12.2.1107.5.1.4.66005.30000017050400361916400003811.3.dcm.zip)

**Comment by tineke01** [comment]
You can try it with this dicom file

**Comment by sedghi** [comment]
This case loads correctly in the OHIF (https://v3-demo.ohif.org/local). Hmm

**Comment by tineke01** [comment]
> 此案例在 OHIF ( https://v3-demo.ohif.org/local ) 中正确加载。唔

I know，But this case loads incorrectly in the cornerstone3D-beta （https://www.cornerstonejs.org/live-examples/local.html）

**Comment by sedghi** [comment]
It seems to be scaling issue, I'll look into it

**Comment by tineke01** [comment]
> It seems to be scaling issue, I'll look into it

是的，我的dicom影像文件的 PixelData 是 Uint16Array，修改成 Float32Array以后，问题得到解决
![微信图片_20220730101712](https://user-images.githubusercontent.com/41686843/181866473-da19c1f2-ea59-4fb4-91b0-7411acb826b1.jpg)
