### ISSUE TITLE
Force reload same image

### ISSUE THREAD

**Issue by yonvaida** [cornerstonejs/cornerstone3D-beta#165]
Is there a method to force reload a image?

**Comment by sedghi** [comment]
Is it because of network problem or you have another usecase?

**Comment by yonvaida** [comment]
i have another case. I get first image in jpeg format sent request to server and get raw image. Same images have same uid so i want to reload image and getpixeldata of raw image.

**Comment by sedghi** [comment]
so is this a problem since the first image is cached? can't you just uncache that? `removeImageLoadObject`

**Comment by yonvaida** [comment]
Thank you it works
