### ISSUE TITLE
How to solve "Your page is NOT cross-origin"

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#166]
When I use the pet/ct case in my own project, the localhost address and DICOM file address are different, and this error occurs.
Chrome 103.0.5060.134 

![image](https://user-images.githubusercontent.com/72963274/183062180-0aafbd59-0d72-4d79-bbdb-85a211771d0d.png)

**Comment by pwespi** [comment]
See
* https://www.cornerstonejs.org/docs/getting-started/scope#browser-support
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

**Comment by abluobo** [comment]
Thank you. The problem is solved.

**Comment by lukepolson** [comment]
How did you fix this? I am struggling to see how those links give the required steps to make a page CORS enabled. Where exactly does one enable this? If I'm using VS Code, do I enable it in the "live-server" application? Or possibly is it a tag/variable I need to set in the html/javascript file? Is it something I need to configure in webpack? Please let me know @abluobo @pwespi .
