### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#169]
cornerstoneWADOImageLoader V4.2.1

![image](https://user-images.githubusercontent.com/72963274/183398248-f3e1b746-a944-4b80-bec0-0c3cb6cc2a44.png)

**Comment by sedghi** [comment]
Can you be more specific of what are you doing?

**Comment by abluobo** [comment]
This error occurs in this scenario:
The [PET-CT Fusion + MIPLayout](https://www.cornerstonejs.org/live-examples/petCT.html) case was used in my project，However, in our system, the image format used is DICOM P10 image. This error will be reported when the image is loaded
![image](https://user-images.githubusercontent.com/72963274/183867547-8395fb8b-e34d-4731-b36d-a86db684bde1.png)
So I want to know how to modify and import DICOM P10 image in the case PET-CT case.

**Comment by sedghi** [comment]
I would suggest to use a simpler example to debug your application. How about trying a simple volume viewport as you find here https://www.cornerstonejs.org/live-examples/volumebasic

**Comment by abluobo** [comment]
I modified the configuration to solve this problem
`const prefix = 'wadouri:'`
