### ISSUE TITLE
the link of cornerstoneWADOImageLoader.js is the same of cornerstoneWADOImageLoader.bundle.min.js 

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#170]
https://github.com/cornerstonejs/cornerstoneWADOImageLoader

Get the distributed unminimized file:

[cornerstoneWADOImageLoader.js](https://unpkg.com/cornerstone-wado-image-loader)
or the distributed minimized file:

[cornerstoneWADOImageLoader.bundle.min.js](https://unpkg.com/cornerstone-wado-image-loader)

the link of cornerstoneWADOImageLoader.js is the same of cornerstoneWADOImageLoader.bundle.min.js

so where can find the file of cornerstoneWADOImageLoader.js?
thanks

**Comment by sedghi** [comment]
Where do you see a link to these bundles?

**Comment by abluobo** [comment]
https://github.com/cornerstonejs/cornerstoneWADOImageLoader
I downloaded the source code of cornerstoneWADOImageLoader and modified the webpack configuration, and then packaged it to solve this problem.
