### ISSUE TITLE
Using custom imageloader for cornerstoneStreamingImageVolume

### ISSUE THREAD

**Issue by yonvaida** [cornerstonejs/cornerstone3D-beta#178]
I tried to use a custom image loader on with cornerstone Streaming image Volume. Problem is that volume is not rerendering when image load promise is resolved. Is there an example or something to use custom imageloader with volume streaming Image. 
Thank you

**Comment by sedghi** [comment]
Yes check it out here https://v3-demo.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463

**Comment by yonvaida** [comment]
Thank you i made custom volume image loader.
