### ISSUE TITLE
crosshairs error

### ISSUE THREAD

**Issue by longuto** [cornerstonejs/cornerstone3D-beta#185]
![image](https://user-images.githubusercontent.com/21220020/186197084-f4a89e27-9ee5-435e-afb1-b4846ca39455.png)
![image](https://user-images.githubusercontent.com/21220020/186197180-dafbbb47-05aa-4d78-9132-66065956a92b.png)
![image](https://user-images.githubusercontent.com/21220020/186198034-175b2400-0078-40c7-83e3-e201d1ba97fa.png)

I'll follow the example(crosshairs) to coding,   but it's has problem.   I don't know how to solve it。

**Comment by longuto** [comment]
I use other tool is ok,  like windowLevelTool，  but crossHair  is error .    my English is not good,   helper me

**Comment by Congritulation** [comment]
Yes, I have encountered the ssame question. I think it caused by system's bug.

**Comment by Congritulation** [comment]
我英语也不好，刚查了一下这个问题，是由于mouseEventHandlers/mouseMove.ts里面的 
// Annotation tool specific
  const toolsWithAnnotations = filterToolsWithAnnotationsForElement(
    element,
    activeAndPassiveTools
  );
这个东西引起的，它来判断工具里是否有annotation数据，但在crosshair初始化的时候，并没有这个数据，因此就会跳到
// Run mouse move handlers for non-annotation tools
  toolsWithoutAnnotations.forEach((tool) => {
    if (typeof tool.mouseMoveCallback === 'function') {
      tool.mouseMoveCallback(evt);
    }
  });
这里执行。但是注意这里的参数只有一个，可是Crosshair要求的参数有两个（have one params, but crosshair need two）
mouseMoveCallback = (
    evt: EventTypes.MouseMoveEventType,
    filteredToolAnnotations: Annotations
  ): boolean =>void
所以在
for (let i = 0; i < filteredToolAnnotations.length; i++)
这里报错了，因为根本没有这个参数

**Comment by Congritulation** [comment]
我找到原因了，你可能是异步执行的问题
// Set volumes on the viewports
  await setVolumesForViewports(
    renderingEngine,
    [
      {
        volumeId,
        callback: setCtTransferFunctionForVolumeActor,
      },
    ],
    [viewportId1, viewportId2, viewportId3]
  );
这里的await，你可能并没有执行
