### ISSUE TITLE
how to set scalingParameters

### ISSUE THREAD

**Issue by DMIAOCHEN** [cornerstonejs/cornerstone3D-beta#208]
a error will throw when run lastest tutorial 

```
Error: options.preScale.scalingParameters must be defined if preScale.enabled is true, and scalingParameters cannot be derived from the metadata providers
```

so how to set preScale 's scalingParameters?

**Comment by sedghi** [comment]
scaling parameters are coming from metadata, so your metadata is missing them. You can add them via a custom metadata provider

**Comment by DMIAOCHEN** [comment]
thanks~

**Comment by luccascorrea** [comment]
Hi,

I tried running the [BasicStack tutorial](https://www.cornerstonejs.org/docs/tutorials/basic-stack) and this error comes up. Shouldn't the tutorial work out of the box by just copying and pasting the code provided?

Thanks

**Comment by sedghi** [comment]
It should, I'll check it and fix it
