### ISSUE TITLE
OrientationAxis.ACQUISITION doesn't work for initial load

### ISSUE THREAD

**Issue by wayfarer3130** [cornerstonejs/cornerstone3D-beta#209]
If one sets the OrientationAxis.ACQUISITION as the initial orientation, then it fails to load because the volume actor isn't set at the initial load time early enough to compute the actual orientation.

**Comment by sedghi** [comment]
Yeah I noticed that and I have a fixed locally. I'll push it

**Comment by rogerbramon** [comment]
thanks @sedghi. Did you have the chance to push the fix?

**Comment by sedghi** [comment]
It is pushed, can you check again?

**Comment by rogerbramon** [comment]
I was able tot test it and seems to be working fine. Thanks @sedghi.
