### ISSUE TITLE
Segmentation performance issue

### ISSUE THREAD

**Issue by zixiCat** [cornerstonejs/cornerstone3D-beta#223]
When I zoom in like the first picture, It's very smooth to draw, however, the drawing is relatively slow when revert to its original size like the second picture

![$4Q89BY6M70%A9W0@X`99HL](https://user-images.githubusercontent.com/47551787/191758779-c7cb8683-b06a-4454-ac3c-098bd910c02e.png)
===
![image](https://user-images.githubusercontent.com/47551787/191759881-c3e5b549-7e86-4ae3-878f-b33c00e132b3.png)

**Comment by zixiCat** [comment]
Has anyone encountered this problem?

**Comment by sedghi** [comment]
can you try with latest?

**Comment by zixiCat** [comment]
@sedghi yep, this problem was fixed in latest version, thank you XD!
