### ISSUE TITLE
Dicomweb via AWS Cloud Front

### ISSUE THREAD

**Issue by luccascorrea** [cornerstonejs/cornerstone3D-beta#230]
Hello,
I realize this question is not exactly related to the library itself but I decided to post it here because I have searched around for a long time and I just can't find an answer or anyone that could give me some direction. So here it goes.

I noticed that the examples on the Cornerstonejs website ([such as this one](https://www.cornerstonejs.org/live-examples/stackbasic)) load DICOM image files and metadata from AWS Cloudfront. My question is: how this is being done? It seems to me that the files were added to S3 and structured in a particular way so that the file paths would match the corresponding WADO-RS endpoint. How was this done? Is there a tool that uploads a set of DICOM files to S3 following that specific directory structure?

Thank you so much for any help. I have been trying to figure this out for so long.

**Comment by chafey** [comment]
https://github.com/RadicalImaging/Static-DICOMWeb
