### ISSUE TITLE
WADO error while running examples on Create-React-App environment

### ISSUE THREAD

**Issue by JonathanGilyadov** [cornerstonejs/cornerstone3D-beta#235]
Hey, I was thrilled to hear about cornerstone 3d arriving, and straight dived into the examples.

**Issue:**
my issue happens once I am trying to reproduce one of the more advanced examples(in my repo I tried the example "crossHairs", but tried "volume basic", which resulted in the same error).

First of all, I'm getting a whole lot of warnings:
<img width="1103" alt="Screen Shot 2022-10-05 at 18 22 09" src="https://user-images.githubusercontent.com/18733907/194098563-8a7cba66-d913-4a96-bd61-6ea1a47d846a.png">

if I ignore them, I am running into this error:
<img width="624" alt="Screen Shot 2022-10-05 at 18 22 48" src="https://user-images.githubusercontent.com/18733907/194098713-6eb91043-0758-42eb-ad9b-3e808e09cecc.png">

I used the initDemo functions from the tutorial, but even if I copy-paste the line `cornerstoneWADOImageLoader.external.cornerstone = cornerstone;` to the top of the file, it still does not work.

for cross-origin isolation, I used a custom proxy which seems to work well.

**How to reproduce:**
clone my repo: https://github.com/JonathanGilyadov/3d

and run:
`npm install`
`npm start`

**Comment by sheep-tech** [comment]
Hi, I've also used a proxy to used Volume API, but I soon run into this problems too. However, it suddenly disappeared and now I get this new issue:
 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/56177667/200338374-9682081e-82f6-4977-ab15-458616d7801e.png)

Basically the @cornerstonejs/core/dist/esm/metaData.js has the providers array that contains all initialized image providers, but when it's accessed, the array becomes empty. This only happens to Volume API, the Stack API works correctly.

**Comment by JonathanGilyadov** [comment]
@swederik any help on this please?

**Comment by heyflynn** [comment]
Fix react + cornerstone + wado image loader

First you need to add craco, rewind or eject the react scripts.
You need to be able to update CWIL to version 4 to support WASM.

```
// Add craco
yarn add @craco/craco copy-webpack-plugin
````

// Add the craco config file
craco.config.js
```
/* craco.config.js */
const path = require(`path`)
const CopyWebpackPlugin = require('copy-webpack-plugin')

const DIST_DIR = path.join(__dirname, './build/static/js')
const SRC_DIR = path.join(
    __dirname,
    './node_modules/cornerstone-wado-image-loader/dist/dynamic-import'
)

module.exports = {
    webpack: {
        alias: {
            'cornerstone-wado-image-loader':
                'cornerstone-wado-image-loader/dist/dynamic-import/cornerstoneWADOImageLoader.min.js'
        },
        plugins: [
            new CopyWebpackPlugin({
                patterns: [
                    {
                        from: SRC_DIR,
                        to: DIST_DIR
                    }
                ]
            })
        ]
    }
}
```



### update package.json to use craco instead of react-scripts for script entry points

   ```diff title="package.json"
   "scripts": {
   -  "start": "react-scripts start"
   +  "start": "craco start"
   -  "build": "react-scripts build"
   +  "build": "craco build"
   -  "test": "react-scripts test"
   +  "test": "craco test"
   }
```

### Delete these lines from index.js in root of src
```diff
- import * as cornerstone from '@cornerstonejs/core';
- import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';

- cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
```

### These get added during the initDemo script when fetching image loaders.

// disable strict mode
```diff
-  <React.StrictMode>
```

It is only run in development, but strict mode does a test on react useEffects to identify any components with unsafe lifecycles.
Unfortunately, bootstrapping cornerstone is an unsafe lifecycle because it works with a mutable state. 
React components need to work with unmutable state.
It’s the reason you need to useEffect
Cornerstone has potentially side effects that would otherwise interrupt reacts lifecycle.

**Comment by makinox** [comment]
Hello, if you log that metadata object you will see that is undefined which means that or those images are not ready in the cache yet, I recommend you to implement a `useEffect` to load the images and then initialize the cornestone viewer with all the metadata of the images already loaded in cache.

**Comment by JonathanGilyadov** [comment]
thank you guys.
your solution worked, and I also tried it without the create react app environment and it worked, so I am closing this.

if I'll have more questions, I will open a new issue.
