### ISSUE TITLE
Can use getElementByClassName instead of firstChild ?

### ISSUE THREAD

**Issue by lambacini** [cornerstonejs/cornerstone3D-beta#252]
https://github.com/cornerstonejs/cornerstone3D-beta/blob/dfdc4bfbf331da40368a4976f3dc199bd355864a/packages/tools/src/drawingSvg/getSvgDrawingHelper.ts#L37

in angularjs, we use nativeElement for rendering element (enabledElement), but nativeElement contains overlayboxes and some other ui components. in this case, cannot add drawings because viewport-element it is not the first element of enabledElement.
if we use getElementByClassName(VIEWPORT_ELEMENT) instead of firstChild, i think it will work.

thank you for your understanding.

![image](https://user-images.githubusercontent.com/943188/196950278-15cadee9-f016-4f55-86da-29b3ce09c958.png)
![image](https://user-images.githubusercontent.com/943188/196950336-91c27742-6b70-4cc5-87ab-88a267bc8962.png)

**Comment by sedghi** [comment]
Interesting bug. Thanks for the report

**Comment by sedghi** [comment]
Do you mind creating a PR for this testing it on your framwork?

**Comment by lambacini** [comment]
i create pr and tested it in my own app and cornerstone examples, it works correctly. but this function will not work correctly if used elsewhere instead of viewport-element.

**Comment by lambacini** [comment]
https://github.com/cornerstonejs/cornerstone3D-beta/pull/268
