### ISSUE TITLE
How to get the 'im' of the current image

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D-beta#261]
I want to display the 'im' of the image while scrolling through the image, but I can't find where to get it
![image](https://user-images.githubusercontent.com/41686843/197746637-2c9d5147-4e2a-43eb-a8f6-2d9ca207ebf3.png)
Something like this

**Comment by sedghi** [comment]
what do you mean by `im`?

You can subscribe to STACK_VIEWPORT_SCROLL event and see where you are in the stack

**Comment by tineke01** [comment]
Can I listen for the ANNOTATION_ADDED event, for example when I add a 'length' and save the 'length' object

**Comment by tineke01** [comment]
![image](https://user-images.githubusercontent.com/41686843/198538498-9272c759-c7a7-49be-bacb-7140a2f7145a.png)
I didn't write it that way
