### ISSUE TITLE
3D volume rendering

### ISSUE THREAD

**Issue by luccascorrea** [cornerstonejs/cornerstone3D-beta#267]
Hi,

I am trying to implement rendering a volume in the way that is displayed in both videos below (the first video was taken from the 3D Slicer program). I couldn't find anything like this in the docs or the examples. Does anyone have a tip on how this could be implemented? I'd just need someone to point me in a direction so I can investigate this further.

I found [this example](https://kitware.github.io/vtk-js/examples/VolumeContour.html) on the VTK.js website that seems to do what I need but I'm not sure how to do these things through Cornerstone3D. It seems like I need to use a `vtkImageMarchingCubes` filter inside a viewport but I'm not sure how it's done.

Thank you!

Video 1: https://www.dropbox.com/s/zgn0a7ubugn2jsx/volume_rendering.mp4?dl=0
Video 2: https://www.dropbox.com/s/p0gnoso0u86h1t9/volume.mp4?dl=0

**Comment by sedghi** [comment]
There are two things here
1. 3D Volume Viewport support: currently our volume viewports are forcing the clipping planes on a tiny tiny slice which is not required for the 3D Volume viewport. So that is not yet implemented. Solution: you can create another volume viewport basically copy pasting the whole thing and just removing the places where we are enforcing the clipping planes
2. Application of filters which is another thing we don't support right now, I guess we need to add api to apply a filter on the image data before feeding it to the mapper (or revise the mapper to get it from the filtered image data)

Happy to review PRs for any of them

**Comment by luccascorrea** [comment]
Got it. Thank you very much for the information @sedghi. I will study the VolumeViewport source code to figure out the best way to do this.

**Comment by luccascorrea** [comment]
Hi @sedghi. 
I am trying to implement option 1 that you suggested, but haven't had much success. I attempted commenting out some parts of the code in both the `VolumeViewport` and `Viewport` classes just to see if it would work before actually creating a new viewport class that implements this new feature. I'm attaching below an image with the git diff of the changes I made just so you have an idea, but this didn't make much of a difference. The first image shows the changes to the `packages/core/src/RenderingEngine/Viewport.ts` file and the second one to the `packages/core/src/RenderingEngine/VolumeViewport.ts` file.

![Screen Shot 2022-10-28 at 09 41 37](https://user-images.githubusercontent.com/9159316/198591975-03061009-d2dd-4f15-a6aa-6f1feea1fbfd.png)

![Screen Shot 2022-10-28 at 09 42 16](https://user-images.githubusercontent.com/9159316/198593001-197eb6b0-e26a-4d3d-bc4f-8810a72a5002.png)

I am using the `TrackballRotateTool` to rotate the camera but it seems like only a frontal plane is shown (as well as another plane in the back when I rotate the volume 180 degrees). You can see what I'm talking about in the video below.


https://user-images.githubusercontent.com/9159316/198594350-d6ae4cc4-06a8-41bd-ba82-a9dce3fa064a.mp4

Sorry to disturb you once again, but could you give me a few pointers?

Thank you very much!

**Comment by sedghi** [comment]
Clipping planes, not clipping range. Remove anywhere we are putting a clipping plane, and let clipping range be actually -infinity to infinity

**Comment by luccascorrea** [comment]
Hi @sedghi. Unfortunately, it's still not working.

I basically made a change to the `resetCamera` method in the `VolumeViewport` class so that the `clippingRange` is set to `-Infinity, Infinity` and commented out the code that adds the two clipping planes. I also made a change to the `Viewport` class so that the clipping range is also set to `-Infinity, Infinity` in the `resetCamera` method (which I think is actually irrelevant, as the `VolumeViewport` class overrides that method and changes the `clippingRange` right after the `super` call). You can see the exact changes below:

![Screen Shot 2022-10-31 at 09 09 24](https://user-images.githubusercontent.com/9159316/199006102-54d64e40-f908-4fa8-b96c-8dabf7498774.png)

![Screen Shot 2022-10-31 at 09 10 15](https://user-images.githubusercontent.com/9159316/199006141-a3330bb7-e75b-4d8b-94ae-f20f672befc5.png)

I still get pretty much the same behavior I described above. It seems like there is only one visible plane in the front and another one in the back. I can't really understand what's going on.


https://user-images.githubusercontent.com/9159316/199006297-989b5f72-5330-4e29-84ab-716996f47706.mov


Thanks for the help!

**Comment by sedghi** [comment]
That is interesting, most likely our tool is wrong, but I don't see why the initial camera should be wrong too. Can you provide a branch?

**Comment by sedghi** [comment]
I had some time to look at this, see my branch [here](https://github.com/cornerstonejs/cornerstone3D-beta/tree/feat/3d-viewport), which is just very ugly implementation, but you get the idea, if you can create a PR I would be happy to review it 

```
cd packages/tools
yarn run example 3dViewport
```

![image](https://user-images.githubusercontent.com/7490180/199148160-0d3d4e97-28d5-45b4-8ff3-73d8af7ea6bc.png)

**Comment by luccascorrea** [comment]
Thank you very much @sedghi!
Yes, that's what I was looking for. I will have a look at the code and submit a pull request. I am a bit caught up with some other things but I'll try to submit it next week.

**Comment by luccascorrea** [comment]
Hi @sedghi. I reorganized the code and implemented a new type of viewport called `VolumeViewport3D`. You can see all my changes [here](https://github.com/luccascorrea/cornerstone3D-beta/tree/feat/new-3d-viewport).

I basically refactored the existing `VolumeViewport` class and extracted all common functionality to an abstract base class that I called `BaseVolumeViewport`. Then both the existing `VolumeViewport` class and the new `VolumeViewport3D` extend it. 

Please let me know what you think and whether there are things you'd like me to change before I send the pull request.

**Comment by sedghi** [comment]
This makes sense to me, can you please go ahead and add the PR (mention this issue as well), and I can review and start the discussion there thanks

**Comment by mongsukim** [comment]
Hello. I'm a beginner developer. 
Thank you for creating such a great library. I'd like to create a 3D volume rendering feature using the cornerstonejs library, similar to what's shown on the https://www.cornerstonejs.org/live-examples/volumeviewport3d page. However, I find the API documentation quite difficult to understand. Would it be possible to see a GitHub repository or example code that implements 3D volume rendering?

**Comment by jianyaoo** [comment]
> Hello. I'm a beginner developer. Thank you for creating such a great library. I'd like to create a 3D volume rendering feature using the cornerstonejs library, similar to what's shown on the https://www.cornerstonejs.org/live-examples/volumeviewport3d page. However, I find the API documentation quite difficult to understand. Would it be possible to see a GitHub repository or example code that implements 3D volume rendering?

@mongsukim  Try the implementation in this demo：https://github.com/jianyaoo/vue-cornerstone-demo/blob/main/src/views/basicUsage/Basic3DRender.vue

**Comment by mongsukim** [comment]
I always encounter the same issue. The error message is as follows:

```
Uncaught (in promise) Error: No volume loader for scheme cornerstoneStreamingImageVolume has been registered
```
Which part should I fix?"


```
const volume = await volumeLoader.createAndCacheVolume(volumeId, {
          imageIds,
        });
```



```
import React, { useState, useEffect, useRef } from 'react';
import {
  volumeLoader,
  RenderingEngine,
  Enums as csEnums,
  setVolumesForViewports,
  CONSTANTS,
  getRenderingEngine,
} from '@cornerstonejs/core';
import initCornerstone from '../initCornerstone';

import cornerstone from 'cornerstone-core';
import cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';

// Constants for volume and viewport setup
const volumeName = 'CT_VOLUME_ID';
const volumeLoaderScheme = 'cornerstoneStreamingImageVolume';
const volumeId = `${volumeLoaderScheme}:${volumeName}`;

const renderingEngineId = 'my_renderingEngine';
const viewportId = '3Dvp';

// Preset options for viewport configuration
const presetOptions = CONSTANTS.VIEWPORT_PRESETS.map((item) => item.name);

const CornerstoneViewer = () => {
  const [preset, setPreset] = useState('CT-Bone');

  const [imageIds, setImageIds] = useState([]);
  const [viewport, setViewport] = useState(null);

  const elementRef = useRef(null);

  // Initialize Cornerstone and rendering engine
  useEffect(() => {
    const init = async () => {
      await initCornerstone();

      const renderingEngine = new RenderingEngine(renderingEngineId);
      const viewportInputArray = [
        {
          viewportId: viewportId,
          type: csEnums.ViewportType.VOLUME_3D,
          element: elementRef.current,
          defaultOptions: {
            orientation: csEnums.OrientationAxis.CORONAL,
            background: CONSTANTS.BACKGROUND_COLORS.slicer3D,
          },
        },
      ];
      renderingEngine.setViewports(viewportInputArray);

      if (imageIds.length > 0) {
        const volume = await volumeLoader.createAndCacheVolume(volumeId, {
          imageIds,
        });
        await volume.load();
        await setVolumesForViewports(
          renderingEngine,
          [{ volumeId }],
          [viewportId]
        );

        const viewportInstance = cornerstone.getViewport(elementRef.current);
        setViewport(viewportInstance);

        viewportInstance.setProperties({ preset });
        viewportInstance.render();
      }
    };

    init();

    // Clean up when component unmounts
    return () => {
      if (elementRef.current) {
        cornerstone.disable(elementRef.current);
      }
    };
  }, [imageIds]);

  // Handle changes to viewport properties
  const handleChange = (type, value) => {
    const viewport =
      getRenderingEngine(renderingEngineId).getViewport(viewportId);
    viewport.setProperties({ [type]: value });
    viewport.render();
  };

  // Handle file input changes and process DICOM files
  const handleFileChange = async (event) => {
    const files = event.target.files;
    const imageIdPromises = [];

    if (files) {
      for (const file of files) {
        const imageId =
          cornerstoneWADOImageLoader.wadouri.fileManager.add(file);
        imageIdPromises.push(imageId);
      }

      const resolvedImageIds = await Promise.all(imageIdPromises);
      setImageIds(resolvedImageIds);
    }
  };

  return (
    <div>
      <div className="form">
        <div className="form-item">
          <label className="label">preset：</label>
          <select
            value={preset}
            onChange={(e) => {
              setPreset(e.target.value);
              handleChange('preset', e.target.value);
            }}
            style={{ width: '150px' }}
          >
            {presetOptions.map((item) => (
              <option key={item} value={item}>
                {item}
              </option>
            ))}
          </select>
        </div>

        <div className="form-item">
          <label className="label">file upload：</label>
          <input
            type="file"
            multiple
            onChange={handleFileChange}
            style={{ width: '300px' }}
          />
        </div>
      </div>
      <div id="demo-wrap">
        <div
          ref={elementRef}
          className="cornerstone-item"
          style={{
            position: 'relative',
            width: '300px',
            height: '300px',
            marginTop: '20px',
            marginRight: '20px',
            padding: '20px',
            border: '2px solid #96CDF2',
            borderRadius: '10px',
          }}
        ></div>
      </div>
    </div>
  );
};

export default CornerstoneViewer;

```

I apologize if the question was inappropriate.

**Comment by jianyaoo** [comment]
Did you execute the `registerVolumeLoader` register function inside the `initCornerstone`  function?

```
import { volumeLoader } from "@cornerstonejs/core";
import {
  cornerstoneStreamingImageVolumeLoader,
  cornerstoneStreamingDynamicImageVolumeLoader,
} from "@cornerstonejs/streaming-image-volume-loader";

export default function initVolumeLoader() {
  volumeLoader.registerUnknownVolumeLoader(
    cornerstoneStreamingImageVolumeLoader
  );
  volumeLoader.registerVolumeLoader(
    "cornerstoneStreamingImageVolume",
    cornerstoneStreamingImageVolumeLoader
  );
  
  volumeLoader.registerVolumeLoader(
    "cornerstoneStreamingDynamicImageVolume",
    cornerstoneStreamingDynamicImageVolumeLoader
  );
}
```

other， I'm not sure if `cornerstone-core` and `@cornerstonejs/core` can be used together, but I recommend harmonizing cornerstone versions
