### ISSUE TITLE
How do we access the labelmaps2D?

### ISSUE THREAD

**Issue by ahlaughland** [cornerstonejs/cornerstone3D-beta#276]
Thanks for Cornerstone as it makes the hard simple and the simple attainable!

I'm having trouble finding the  `labelmaps2D` on the `labelmap3D`. I searched the Issues and didn't find any infos regarding labelmaps2D.

Here is the scenario I am in:

DCMJS requires that there is a `labelmaps2D` on the `labelmap3D` sent to it by cornerstone:
https://github.com/dcmjs-org/dcmjs/blob/9023d1eb9f722a68f117dedc5e9088a70d907f38/examples/createSegmentation/index.html#L155

I'm drawing a segment and getting the labelmapVolume:
`const  labelmaps3D = cornerstoneCore.cache.getVolume(segmentationId);`

But when I pass the labelmaps3D to dcm.js:
```
const segBlob = dcmjs.adapters.Cornerstone.Segmentation.generateSegmentation(
            images,
            labelmaps3D,
            options
          );
```

It throws and error that `labelmaps2D.length` is `undefined`:
![image](https://user-images.githubusercontent.com/17124113/199257778-877c7ba9-efd2-4c53-a4d8-19f981eb12d1.png)

Dcm.js:
![image](https://user-images.githubusercontent.com/17124113/199258019-ac62d22e-85af-4145-89cc-a2ddbb87f97d.png)

This is because there is/are no `labelmaps2D `on the labelmap:
![image](https://user-images.githubusercontent.com/17124113/199256660-aabacce8-04fb-43f5-8762-cfc3c51f1069.png)

How would I acquire the labelmaps2D required by dcm.js?

**Comment by sedghi** [comment]
Hi, cornerstone3D does not have labelmap2D like cornerstone legacy had. Do you want to load a DICOM SEG? I have a big PR coming up to OHIF very soon that adds the support with OHIF v3 and cornerstone3D

**Comment by ahlaughland** [comment]
HI Seghi. Yes we would like to load (and save) the DICOM SEG. Can you pass along a link to your PR or what branch you are merging it into?

Thanks again!

**Comment by sedghi** [comment]
Yes, I will post it here for you

**Comment by ahlaughland** [comment]
Hi Sedghi. I see you have created a PR for SEGs: https://github.com/OHIF/Viewers/pull/3015

This is some amazing work and I am excited to review it an learn how the code works. 

I will close this issue and track changes from the PR.

Thanks again!
-Andrew
