### ISSUE TITLE
Is there a way to have a cleanup in a Tool

### ISSUE THREAD

**Issue by doepnern** [cornerstonejs/cornerstone3D-beta#277]
Hey, 
is there any way to have a safe way to cleanup listeners attached during a tools lifecycle. I want to listen to stack change events on a specific element and need to clean them up when the tool is destroyed. This works with onSetToolDisabled, but that function is not called, for example when destroyToolGroup is called.
Thanks!

**Comment by sedghi** [comment]
onSetToolDisabled should be called as I see [here](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/tools/src/store/ToolGroupManager/ToolGroup.ts#L356-L357)
