### ISSUE TITLE
OrientationMarkersTool & ScaleOverlayTool Could you update to the current version

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D-beta#290]

**Comment by sedghi** [comment]
Can you update the description for the isse?

**Comment by tineke01** [comment]
> 你能更新一下这个问题的描述吗？

I hope has OrientationMarkersTool and ScaleOverlayTool in cornerstoneTools of cornerstone3D,I want to use it in volume viewport

**Comment by tineke01** [comment]
![image](https://user-images.githubusercontent.com/41686843/201290673-2cc62206-0c26-48b6-bbdd-14d61d7284dd.png)
I want to have a scale on the volume viewport, the old version was implemented by ScaleOverlayTool, but I didn't find this tool in the 3D version

**Comment by tineke01** [comment]
I tried to move the old version of the code to the new version, but I was unsuccessful，I hope you can help me realize the function of this scale line

**Comment by sedghi** [comment]
Can you create a draft PR to our Cornerstone3D repo, I can investigate and help you to implement this feature

**Comment by tineke01** [comment]
> Can you create a draft PR to our Cornerstone3D repo, I can investigate and help you to implement this feature
#298 
I have created a draft  PR ，I just created the file. Please help me complete this function, thanks
