### ISSUE TITLE
StackViewer not working due to offset "out of bounds"

### ISSUE THREAD

**Issue by JwRicauter** [cornerstonejs/cornerstone3D-beta#306]
Hi,

I have my app that it was working nice, but suddenly this error jumps out:

`Uncaught (in promise) RangeError: offset is out of bounds
    at Float32Array.set (<anonymous>)
    at StackViewport._updateVTKImageDataFromCornerstoneImage (StackViewport.ts:1366:1)
    at StackViewport._updateActorToDisplayImageId (StackViewport.ts:1720:1)
    at StackViewport.successCallback (StackViewport.ts:1559:1)
    at StackViewport.ts:1584:1`
    
 I don't know what's happening because the image stack viewer was working. I have in my backend NIFTI files from wich I divide it into dicom files and send it to the client.
 
 `
 class DicomWeb(generics.GenericAPIView):

    class DicomRenderer(renderers.MultiPartRenderer):
        media_type = 'multipart/related; type=application/octet-stream; transfer-syntax=*'

        def render(self, data, accepted_media_type=None, renderer_context=None):
            return data

    renderer_classes = (DicomRenderer,)

    def get(self, request, study, series, instance, frame):
        case_id = study
        img_id = series
        series_dcms_dir = get_series_dcms_dir(case_id, img_id)
        dicom_path = f'{series_dcms_dir}/{instance}.dcm'
        dicom = pydicom.dcmread(dicom_path)
        data = {}
        data[str(dicom_path)] = (
            'dicomfile', dicom.PixelData, 'application/dicom')

        # encode as multipart_related
        body, content_type = encode_multipart_related(fields=data)
        response = HttpResponse(body, status=200)
        response['Content-Type'] = 'binary/octet-stream'
        return response
 `
any clue?

**Comment by andrei0807** [comment]
Same issue
![image](https://user-images.githubusercontent.com/32348752/218114222-f78729e9-62cd-43cb-a964-fea5520621a7.png)
