### ISSUE TITLE
Question: How does VolumeViewport implement the setImageIdIndex method like StackViewport？

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#332]
[StackViewport](https://www.cornerstonejs.org/api/core/class/StackViewport) provides the [setImageIdIndex](https://www.cornerstonejs.org/api/core/class/StackViewport#setImageIdIndex) method, but [VolumeViewport](https://www.cornerstonejs.org/api/core/class/VolumeViewport) does not. How does VolumeViewport implement the setImageIdIndex method?

**Comment by lambacini** [comment]
Maybe this method can help you.

cornerstoneTools.utilities.jumpToSlice(element, {
            imageIndex: sliceNumber
        });

https://github.com/cornerstonejs/cornerstone3D-beta/blob/d49cf773a09db4e83ab53c85b8f615db7e7c3f09/packages/tools/src/utilities/viewport/jumpToSlice.ts#L22

Or you can check the function below.
(https://github.com/cornerstonejs/cornerstone3D-beta/blob/d49cf773a09db4e83ab53c85b8f615db7e7c3f09/packages/tools/src/utilities/scroll.ts#L18)

**Comment by abluobo** [comment]
@lambacini Thank you
