### ISSUE TITLE
8-bit colored images are not displayed properly 

### ISSUE THREAD

**Issue by Zaid-Safadi** [cornerstonejs/cornerstone3D-beta#338]
When using wado-uri or file system to load an ultrasound 8-bit image with with "Photometric Interpretation (0028,0004)" "RGB" and "Samples Per Pixel (0028,0002)" "3" the image rendering is corrupted. 

There are different rendering results using CPU or WebGL, You can try this in the Examples:
1. DICOM P10 from local file system (CPU): image is completely corrupted 
2. DICOM P10 from local file system: Image is rendered correctly but the W/L values are off. Compare this when applying the same WW/WC on other DICOM viewer (desktop or OHIF WADO-RS) 

CPU Example Result:
![image](https://user-images.githubusercontent.com/10813109/208570262-6e3796b4-568d-482c-b24f-fda6cf65abfb.png)

WebGL Example Result:
![image](https://user-images.githubusercontent.com/10813109/208570558-b54fec05-0563-4246-b621-a7afd0e94a9f.png)

Desktop Viewer (notice the non-organ part is black):
![image](https://user-images.githubusercontent.com/10813109/208570654-a0d3d7c7-d29e-41a6-b9f5-c25e600b9b00.png)

**Comment by Zaid-Safadi** [comment]
This is an anonymized dataset that reproduces the issue: https://1drv.ms/u/s!AluyBah_ueAcg8EHRae6kDbLtkR5sA?e=c3kRnR

I checked the cornerstone3d example and it configures cornerstoneWADOImageLoader as recommended in this issue https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/498: 
  ```js
cornerstoneWADOImageLoader.configure({
    useWebWorkers: true,
    decodeConfig: {
      convertFloatPixelDataToInt: false,
    },
  });
```

**Comment by Zaid-Safadi** [comment]
I was able to track down the corrupted display in:

> DICOM P10 from local file system (CPU): image is completely corrupted

to the StackViewport useRGBA flag here:
https://github.com/cornerstonejs/cornerstone3D-beta/blob/5605a39b17749f4f1d0bf6f3ee6f5ee9be492be8/packages/core/src/RenderingEngine/StackViewport.ts#L1520

Once I set the useRGBA to true, the image is rendered to match the way it is rendered in point 2:

> DICOM P10 from local file system: Image is rendered correctly but the W/L values are off

@sedghi any idea what could be the problem with RGB <--> RGBA?

The invalid W/L seems to be carried over from old cornerstone as I can reproduce it there. Interesting that it works fine when loading the image in WADO-RS in OHIF

**Comment by sedghi** [comment]
As I see the desktop and webgl path matches each other, no? I don't understand `Desktop Viewer (notice the non-organ part is black):`

So you are saying the failed CPU path is corrected if useRGBA is true right? I guess that is a bug and it should use flag as true (which I thought it is true by default), since CPU webgl uses the A (in rgbA) to render greyscale so it need the useRGBA

**Comment by sedghi** [comment]
I'm 99.99% sure that was a mistake by me adding useRGBA to false for CPU route.
