### ISSUE TITLE
setColormapGPU not implemented yet

### ISSUE THREAD

**Issue by ssokmen** [cornerstonejs/cornerstone3D-beta#359]
Hi, Do u have any progress about using colormap for stackviewport?

**Comment by sedghi** [comment]
Not that way (through stackViewport api), but you can set colormaps manually like this https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/utils/demo/helpers/setPetColorMapTransferFunctionForVolumeActor.js#L5

**Comment by ssokmen** [comment]
Thanks for the inspiration. I really appreciate it. Here I am adding a code block for the convenience of other friends who may be interested in it.

 ```
let ActorEntry = viewport.getActor(viewport.id);`
let actor = ActorEntry.actor;
 actor.getProperty().setRGBTransferFunction(0, cfun);
viewport.render();
```
