### ISSUE TITLE
Bug: Cornerstone Examples

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D-beta#371]
All examples are giving error (https://www.cornerstonejs.org/docs/examples)

![image](https://user-images.githubusercontent.com/50026015/212931716-3ba1185a-6f89-4a68-8d30-6e2821ae854c.png)

**Comment by sedghi** [comment]
Thanks for the report https://github.com/cornerstonejs/cornerstone3D-beta/pull/373
