### ISSUE TITLE
Reset camera bug when rotation happens on StackViewport

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D-beta#372]
New small bug with latest version : https://www.cornerstonejs.org/live-examples/stackapi

Reproduce via
- Rotate
- Flip
- Reset => does not reset

( note : reset work on rotate, flip, flip + rotate, but not on rotate + flip

funnier :  rotate, flip H, flip V, reset : works)

**Comment by jbocce** [comment]
Another issue found...

rotate + flip + next image is NOT is the correct orientation

**Comment by jbocce** [comment]
PR: https://github.com/cornerstonejs/cornerstone3D-beta/pull/388

**Comment by jbocce** [comment]
Various scenarios to test - also try permutations of each:

rotation + flip + next image
rotation + flip + reset
rotation + flip + next image + absolute rotation
rotation + flip + next image + delta rotation
rotation + flip + delta rotation
