### ISSUE TITLE
Double click detection

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D-beta#375]
Currently the double click on a viewport when an annotation tool is active will start the annotation/rendering loop which is not great since that means to App can run callbacks on double click.

There should be a timeout for the [mouseDownlistener](https://github.com/cornerstonejs/cornerstone3D-beta/blob/feat/sphere-surface-cut/packages/tools/src/eventListeners/mouse/mouseDownListener.ts#L86-L141) set so that a double click is distinguished from a single click. Since otherwise, the double click will be triggered as : single click (first click) + double click (when second click happens)

**Comment by jbocce** [comment]
Related PR: https://github.com/cornerstonejs/cornerstone3D-beta/pull/382

**Comment by jbocce** [comment]
Subsequent PRs to fix bugs:

- https://github.com/cornerstonejs/cornerstone3D-beta/pull/417
- https://github.com/cornerstonejs/cornerstone3D-beta/pull/416
