### ISSUE TITLE
Property 'setStack' does not exist on type 'IVolumeViewport'

### ISSUE THREAD

**Issue by lohith95** [cornerstonejs/cornerstone3D-beta#383]
Hello,

I recently started working with the cornerstone3d and trying to render a DICOM image in angular.
i made all the setup as per [document ](https://www.cornerstonejs.org/docs/tutorials/basic-stack)but i am facing an error for the below code.
`viewport.setStack(imageIds, 60);`

Here is the error
> Property 'setStack' does not exist on type 'IVolumeViewport'

Can i get some help.

**Comment by lambacini** [comment]
yes because you need to set volume to IVolumeViewport. setStack exists only for stackviewport. If you want to load volume and set viewport, check the link below.

https://www.cornerstonejs.org/docs/tutorials/basic-volume
