### ISSUE TITLE
add getImage (cornerstone legacy) as a utility

### ISSUE THREAD

**Issue by sedghi** [cornerstonejs/cornerstone3D-beta#390]
In cornerstone legacy we had `getImage` which would return the `image` object from the enabled element. https://github.com/cornerstonejs/cornerstone/blob/master/src/getImage.js

Since our rendering pipeline has changed and we have removed that function, to accomodate migrations from legacy to cornerstone3D we should add a new utility function `utilities.getCornerstoneLegacyImageForStackViewport` that would return the [image object. ](https://www.cornerstonejs.org/docs/concepts/cornerstone-core/images)

**Comment by jbocce** [comment]
As discussed with @sedghi, we will call it `utilities.getImageLegacy` instead
