### ISSUE TITLE
problem with the state in @cornerstone/tools 

### ISSUE THREAD

**Issue by mutik0137** [cornerstonejs/cornerstone3D-beta#426]
Hi! First of all, thank you for your project. It's very cool, I've been using it for almost a year and built a small web viewer on cornerstone.
When switching to cornerstone 3d, there were some difficulties with annotations state.
If there is no FrameOfReferenceID tag in the dicom file, then state will look like in 1 picture
![image](https://user-images.githubusercontent.com/48162503/217538479-f1e34491-0d7f-4c47-9cec-8549b80d8236.png)
I'll attach the file
[aafddfdf-7b1f-4771-9bb4-15b735575b03.zip](https://github.com/cornerstonejs/cornerstone3D-beta/files/10685835/aafddfdf-7b1f-4771-9bb4-15b735575b03.zip)

**Comment by sedghi** [comment]
FrameOfReferenceID is a type 1 dicom tag so it should be provided, you need to export your dicoms correctly

**Comment by mutik0137** [comment]
I often meet such dicoms. Perhaps the problem is in the equipment.
So I will have to process such cases.

Another question about tools coordinates.
Previously, the origin for (x,y) for CT was the upper-left corner of the canvas. Now the origin of the coordinates is approximately in the middle of the canvas. Can you please tell me how this point is calculated for (x,y). I fill in the annotation.tools manually

**Comment by mutik0137** [comment]
I filled in PlanarFreehandROI manually
![image](https://user-images.githubusercontent.com/48162503/220620486-5c13f922-43e6-4308-ba3b-b9f6ad79a42d.png)
![image](https://user-images.githubusercontent.com/48162503/220620509-cf1d97d1-8cf1-4923-8199-99ed3f26f105.png)
You can see that the coordinates of the shape start at the point (0,0). I expected it to be the top left corner of the image, but it's about in the middle of the image. Does it work correctly? If so, how is the origin calculated?

**Comment by sedghi** [comment]
Oh I see, the coordinates for annotations in cornerstone3D are all in world Coordinates. If your previous coordinates were canvas or image you can easily convert them to world using 

`canvas -> world` via `viewport.canvasToWorld`
`image to world` using `core.utilities.imageToWorldCoords`

**Comment by mutik0137** [comment]
Oh, thx you
