### ISSUE TITLE
Error: SharedArrayBuffer is NOT supported in your browser

### ISSUE THREAD

**Issue by qianjinlong7** [cornerstonejs/cornerstone3D-beta#431]
I want to know what I should do in this situation.
This happens when I call createAndCacheVolume.
![2023-02-10 17-43-58 的屏幕截图](https://user-images.githubusercontent.com/95606828/218058812-08776a93-c7cb-4fd9-a6f6-b7eb44b1d2d8.png)

**Comment by sedghi** [comment]
It means you haven't set the correct headers. Look what we do in the netlify.toml

**Comment by qianjinlong7** [comment]
> thanks a lot!

**Comment by xiaoxiao5** [comment]
@qianjinlong7 excuse me.How was the problem solved?

**Comment by qianjinlong7** [comment]
> @qianjinlong7 excuse me.How was the problem solved?

我用的是React框架，在**webpackDevServer.config.js**文件中为headers添加两个属性
`'Cross-Origin-Embedder-Policy': 'require-corp',
 'Cross-Origin-Opener-Policy': 'same-origin',`
如图
![2023-03-14 14-52-18 的屏幕截图](https://user-images.githubusercontent.com/95606828/224919275-02e34ed9-4df2-4642-9010-58668dd14076.png)
重新运行即可

**Comment by xiaoxiao5** [comment]
@qianjinlong7 谢谢你，完美解决
