### ISSUE TITLE
viewport is not a BaseVolumeViewport

### ISSUE THREAD

**Issue by HussainHaider** [cornerstonejs/cornerstone3D-beta#434]
I'm utilizing cornerstone3D with reactjs and displaying a DICOM file using the VolumeBasic example from [VolumeBasic example](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/core/examples/volumeBasic/index.ts) . I made a slight modification to the example by using my own ImageIds obtained from an API call. However, I'm encountering the following error.

![Screenshot from 2023-02-15 15-12-26](https://user-images.githubusercontent.com/21118650/218998613-2e0caaa7-a16e-4f7a-93a3-5292c33e3d68.png)

**Comment by sedghi** [comment]
what have you changed ? only the imageIds?

**Comment by HussainHaider** [comment]
I mean imageIds and the wadoRsRoot. Can you plz tell me what should be the return type of the DICOM file from the server? I guess you getting 'image/jls' from server.

**Comment by HussainHaider** [comment]
Change the ViewportType from  `ViewportType.ORTHOGRAPHIC` to `ViewportType.PERSPECTIVE`
