### ISSUE TITLE
How to use CT image to build 3d

### ISSUE THREAD

**Issue by Rookieamatuer** [cornerstonejs/cornerstone3D-beta#445]
I'm trying to implement a function that click the structure, or focus, and grow through the region, or see if the api is provided to realize the annotation and generate 3D.But I can't find an api to build 3d images

**Comment by sedghi** [comment]
Could you please explain more no what you want to achieve? Do you need a 3D segmentation tool?

**Comment by Rookieamatuer** [comment]
The function I want to implement is a tool like freehandScissor tool to preserve the lesion part and then rebuild it into 3D models. Build the model with specified part instead of hole CT images. And the part is chosen by users themselves. Are there any tools that users can annotate specified part in one CT image and then automatically apply in all CT images?

**Comment by sedghi** [comment]
freehandscissor tool let you annotate part of the CT

**Comment by Rookieamatuer** [comment]
Can it cut multi-layer images? For example, if I select a part on a CT, other CT images can automatically select the corresponding part, like this?

**Comment by sedghi** [comment]
I'm not sure what you mean by cutting, do you have video recording showing what you mean in other viewers?

**Comment by Rookieamatuer** [comment]
This is still an idea for me. I wondered if there is any api that can build a 3D model. I want to implement it as the first step. I'm new to this project, so I think what I should do first is to know more about this project. Thank you for your answers these days.

**Comment by Rookieamatuer** [comment]
Yes, exactly. Where can I find the code or api that implement this effect.

**Comment by sedghi** [comment]
You can see here https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/core/examples/volumeViewport3D/index.ts

But I recommend our docs for sure https://www.cornerstonejs.org/docs/category/getting-started

**Comment by Rookieamatuer** [comment]
Thanks a lot!
