### ISSUE TITLE
Cannot destructure property 'correctedImage' of 'ptSeriesModule' as it is undefined.

### ISSUE THREAD

**Issue by qianjinlong7** [cornerstonejs/cornerstone3D-beta#455]
This error occurred when I ran this method in my project to get the PET imageIds.
![2023-03-02 14-46-03 的屏幕截图](https://user-images.githubusercontent.com/95606828/222352076-65e25363-8ba2-44a2-890d-069160a1f159.png)
![2023-03-02 14-33-49 的屏幕截图](https://user-images.githubusercontent.com/95606828/222352099-b93caa04-90e2-497b-a63f-9cb859668e4e.png)
I don't know what I'm gonna do with this. Can you help me.

**Comment by sedghi** [comment]
is it our server or your dicom server?

**Comment by qianjinlong7** [comment]
> is it our server or your dicom server?

This problem occurred in chromium low version of Electron, and when I upgraded Electron the problem was resolved, although I don't know what the problem was.
