### ISSUE TITLE
Fusion in Electron

### ISSUE THREAD

**Issue by qianjinlong7** [cornerstonejs/cornerstone3D-beta#457]
When I use setPetColorMapTransferFunctionForVolumeActor in Electron
![2023-03-03 17-57-47 的屏幕截图](https://user-images.githubusercontent.com/95606828/222690947-c69c08d0-d2d7-48c3-89c6-64548568e19c.png)
May I ask why

**Comment by sedghi** [comment]
hmmm, does it work normally in chrome?

**Comment by qianjinlong7** [comment]
> hmmm, does it work normally in chrome?

That problem is solved, thank you.

**Comment by sedghi** [comment]
Could you please add the solution here for future persons seeing the same problem? Thanks!

**Comment by qianjinlong7** [comment]
The problem occurred when I was using a low version of electron, and the code was running in the corresponding low version of chromeium, which is version M96. Just upgrade the electron version to fix the problem.

**Comment by David2k13** [comment]
> The problem occurred when I was using a low version of electron, and the code was running in the corresponding low version of chromeium, which is version M96. Just upgrade the electron version to fix the problem.当我使用低版本的电子时，出现了问题，并且代码在相应的低版本的铬（即 M96 版本）中运行。只需升级电子版本即可解决问题。

I have encountered the same problem, but I don't understand the version you are referring to. Is it VTK or Cornerstone? Can you be more specific

**Comment by David2k13** [comment]
> Electron



> > The problem occurred when I was using a low version of electron, and the code was running in the corresponding low version of chromeium, which is version M96. Just upgrade the electron version to fix the problem.当我使用低版本的电子时，出现了问题，并且代码在相应的低版本的铬（即 M96 版本）中运行。只需升级电子版本即可解决问题。
> 
> I have encountered the same problem, but I don't understand the version you are referring to. Is it VTK or Cornerstone? Can you be more specific我遇到了同样的问题，但我不明白你所指的版本。是 VTK 还是 Cornerstone？你能说得更具体一点吗

Oh, you're talking about Electron, I'm in a web browser
