### ISSUE TITLE
Any way to decrease Cornerstone3D's bundle size?

### ISSUE THREAD

**Issue by RPGillespie6** [cornerstonejs/cornerstone3D-beta#465]
Cornerstone legacy basic example:

https://rawgit.com/cornerstonejs/cornerstone/master/example/changeimage/index.html

Cornerstone.js is 65KB compressed over the wire and basic example took 100ms to fully load when run locally (50ms with cached files).

Cornerstone3D basic example:

https://www.cornerstonejs.org/live-examples/stackbasic

Cornerstone.js is now 1MB compressed and basic example took 500ms to fully load when run locally (150ms with cached files).

This is definitely noticeable from a page loading/responsiveness standpoint. Cornerstone legacy pages load and are ready to use lightning fast whereas Cornerstone3d pages feel more sluggish to load with more flickering and such before everything is ready by comparison.

It seems like `RenderingEngine` is the culprit since importing that alone increases bundle size by 2MB uncompressed. Is the reason for the bloat in `RenderingEngine` VTK or something? I'm just curious if this will ever be addressed or if going forward the new cornerstone is just always going to have 2MB minimum bundle size and slower initial page loads.

**Comment by sedghi** [comment]
Hi, great comment. I was wondering how do you calculate the 1MB? 

https://bundlephobia.com/package/@cornerstonejs/core@0.33.1

**Comment by RPGillespie6** [comment]
Wow, the one you linked it quite a bit smaller than what I was seeing! I wonder if 

Here's what I did:
- I cloned `cornerstone3D-beta` repo
- I navigated to `packages/tools/examples/tutorial/index.ts` and replaced the contents of that file with:
```
import { RenderingEngine } from '@cornerstonejs/core';
console.log("RenderingEngine", renderingEngine);
```
- I then ran `npm run build-all-examples`
- I checked the size of `tutorial.js` in `.static-examples`:
```
ls -lh ./static-examples/tutorial*
-rw-r--r-- 1 user user  862 Mar  7 11:29 tutorial.html
-rw-r--r-- 1 user user 2.7M Mar  7 21:49 tutorial.js
-rw-r--r-- 1 user user 2.8M Mar  7 21:49 tutorial.js.map
```
- I then gzipped the js bundle and got:
```
-rw-r--r-- 1 user user 466K Mar  7 21:50 tutorial.js.gz
```

So that's ~.5MB with only `RenderingEngine` imported and nothing else. If I add a viewport and init code required to get the basic stack example working from [here](https://github.com/cornerstonejs/cornerstone3D-beta/blob/main/packages/core/examples/stackBasic/index.ts), then bundle size increases to 1MB compressed.

I suppose that's not really a fair metric though since maybe the `npm run build-all-examples` script is not optimally bundling for my use case.

**Comment by RPGillespie6** [comment]
I was able to get the `console.log(RenderingEngine);` bundle size down to 213kb (compressed) using esbuild - `npx esbuild src/index.ts --bundle --minify --outfile=bundle.js`. 

I tried using rollup to see if I could get it even smaller, but I was having trouble getting rollup to work. Anyway, I can see the bundler pulling in `@kitware/vtk.js` so I think a minimum viable bundle for any application is going to be bigger than vanilla `@cornerstonejs/core`, it's going to be `@cornerstonejs/core` + any external packages that it references.

**Comment by sedghi** [comment]
the build examples don't minify, see webpack recipes we have

**Comment by sedghi** [comment]
It will only pull parts of vtk.js that it needs, use the esm build that we have

**Comment by RPGillespie6** [comment]
Thanks, I'll check out the webpack recipes. 

For your other comment you are saying to just use es modules directly in browser without using a bundler (i.e. `<script src="./cornerstone_core.js" type="module">` or something like that? That would be pretty sweet, where do I find esm builds or build script?

(once I figure this out I can submit a PR that updates the docs if you like so you can point others to it in the future)

**Comment by sedghi** [comment]
You can try it. Not sure it will work because of the dynamic imports that we have for codecs in the CornerstoneWADOImageLoader though. Is there any reason you don't use a bundler that will handle all of this?

**Comment by RPGillespie6** [comment]
With esbuild I was able to get sub volume viewport working with a bundle in the sub MB range, I think we can close this

**Comment by sedghi** [comment]
Thanks, if you would like to share your answer, please don't hesitate to let me know, I can add it to the docs, or just comment even here for future devs looking for an answer
