### ISSUE TITLE
Inverted contrast in some CT studies using MPR, Crosshairs, Volume loader viewer configuration

### ISSUE THREAD

**Issue by makinox** [cornerstonejs/cornerstone3D-beta#467]
Hello guys, I hope you are having a nice day.
I open this issue because I think that I'm having an issue in some CT studies.
I'm creating a little viewer using this base configuration https://www.cornerstonejs.org/live-examples/crosshairs and in the 20% of the studies I'm testing are showing with bad resolution and wrong colors like in the following image.
<img width="1001" alt="Screenshot 2023-03-08 at 3 53 06 PM" src="https://user-images.githubusercontent.com/24579681/223847307-a099f4ef-4fe6-4742-8125-26b0b77ef243.png">
Can you tell me if there is some incompatibility or maybe an extra step in the configuration that needs to be done?
Thanks.

**Comment by sedghi** [comment]
Do you have the data which is anonymized and whether you can share it?

**Comment by makinox** [comment]
Yes, this is a study with the problem https://drive.google.com/file/d/1leBVI_0JypNdmLj0szzHTmztMuJCTpSp/view?usp=share_link

**Comment by sedghi** [comment]
There are 9 series in this folder, please give me the one that you are showing above 

![image](https://user-images.githubusercontent.com/7490180/224755738-7c54165e-91c1-4113-aec3-ff2e9f216432.png)

**Comment by makinox** [comment]
Serie_1 -  ef60b63f-950e-4b24-9910-03d422432952 Is the serie in the screenshot, but you can see the effect in most of the series in that study.

**Comment by sedghi** [comment]
I can't help you, since I asked for anonymized data but you didn't follow the instructions.

**Comment by makinox** [comment]
Hello can you give me some information about your last response, this study was found in public seeders to test.
I shared all the study in case you need some special metadata in the case the serie with the problem hadn’t a particular key metadata.

**Comment by sedghi** [comment]
You SHOULD NOT share un-anonymized data in public

**Comment by makinox** [comment]
Thanks for the feedback, I'm to double-check every tag of this study in particular to make sure everything is anonymized before sharing it again.
And I also want to clarify that I encounter the original problem in many studies of similar characteristics, but reviewing the library I didn't find a solution yet, so I think this shouldn't be closed yet, I will appreciate if you can point me in any direction.
I really love what you are doing here.
