### ISSUE TITLE
modification of scalarData not work

### ISSUE THREAD

**Issue by MYWpro** [cornerstonejs/cornerstone3D-beta#540]
Hello, I tried using a button to trigger the modification of scalarData for segmentionVolume and then re render Viewports, but when I triggered using the button, the segmentation did not appear in the view as I expected.

**Comment by sedghi** [comment]
have you called .modified? you can take a look at `segmentationDataModifiedEventListener` to see how we trigger updates, you might need to have it get uploaded to gpu again

**Comment by sedghi** [comment]
have you called .modified? you can take a look at `segmentationDataModifiedEventListener` to see how we trigger updates, you might need to have it get uploaded to gpu again
