### ISSUE TITLE
Drop in performance when showing/hiding a segmentation representation 

### ISSUE THREAD

**Issue by rogerbramon** [cornerstonejs/cornerstone3D-beta#546]
After updating to the latest version, I noticed that showing or hiding a segmentation representation (tested only on labelmap) takes more than a second to react when it used to be instantaneous.

After running a profile, I suspect that the problem was introduced on #477 from @sedghi, however I was not able to check it further because of an error when using the prior version.

Evaluating the profile, it's seems that the cause is in `getSegmentationIndices` and the amount of times that `scalarData.forEach` is called. (`setToolDisabled` happens twice because I have two ToolGroups)

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/330441/231207343-13d8d669-f8df-4d71-8837-012eb8011f66.png">

This is the time spent on `@ segmentationVisibility.js:12:1`:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/330441/231207108-9bf02b1d-819e-472a-813f-5da2ca732f4b.png">

Let me know if you need any more info. Thanks

**Comment by sedghi** [comment]
I guess I know what you are talking about, I will look into this. How big is your segmentation? how many segments you have?

**Comment by rogerbramon** [comment]
In that case, it was a segmentation of 11 segments of 50–100 voxels. It used to be instantaneous with a version of 2 months ago, now the interface hangs for a couple of seconds.

**Comment by sedghi** [comment]
I'm surprised it happens for 11 segments or so, here is a 43 segment SEG in OHIF, and does not hang for me 

https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.12.2.1107.5.2.32.35162.30000015050317233592200000046

**Comment by rogerbramon** [comment]
@sedghi I would like to know your idea regarding this issue. Otherwise, I'll try to provide a PR. Thanks!

**Comment by sedghi** [comment]
It is the getSegmentationIndices, that is taking long. I can't think of any other performant way to implement that from the top of my head. Other alternative solutions might be to keep track of indices in the SegmentantionData state but keeping that in sync might get crazy ...

**Comment by sedghi** [comment]
oh I did a forEach? No it should be a for indeed for browser optimizations. Yes I appreciate a PR
