### ISSUE TITLE
The window level and window width of the image are not displayed properly，

### ISSUE THREAD

**Issue by tineke01** [cornerstonejs/cornerstone3D-beta#550]
![image](https://user-images.githubusercontent.com/41686843/231717020-9510c12c-c681-48c8-9549-5f2e4a54f50c.png)
OHIF is true
![image](https://user-images.githubusercontent.com/41686843/231717239-b5e56337-77d1-44b1-98e5-76d94245ec98.png)

**Comment by tineke01** [comment]
i use imageLoader.loadAndCacheImage(imageId) load image

**Comment by tineke01** [comment]
i should use loadImage to load image

**Comment by yuyifly82** [comment]
Can you tell me how you solved this problem?I have been troubled for 2 days now。
