### ISSUE TITLE
Missing "PRE_STACK_NEW_IMAGE" for cpu?

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D-beta#558]
"gpu" already has "pre stack" event but another "cpu" doesn't.

### _loadAndDisplayImageGPU
https://github.com/cornerstonejs/cornerstone3D-beta/blob/a2318cba4eb4e0719c892b85ac6ce3020f9176ca/packages/core/src/RenderingEngine/StackViewport.ts#L1840-L1846

**Comment by sedghi** [comment]
we haven't put much effort in the CPU path and is not a priority at the moment. If you want that event I would be happy to review your PR

**Comment by jlopes90** [comment]
https://github.com/cornerstonejs/cornerstone3D-beta/pull/565
