### ISSUE TITLE
Annotation: duplicate event "annotation added"?

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D-beta#570]
When drawing annotation it fires "annotation added" event but then "triggerAnnotationAddedForFOR" means get all viewports and fire "annotation added" event again.

https://github.com/cornerstonejs/cornerstone3D-beta/blob/cc3ce18f1c601fc911d8866987ae369a8f4c28df/packages/tools/src/stateManagement/annotation/annotationState.ts#L87-L96

**Comment by iamiota** [comment]
same +1, putting `triggerAnnotationAddedForFOR` in `else` can solve it.
