### ISSUE TITLE
Turn off smooth render during visualization in volume.

### ISSUE THREAD

**Issue by zhoualibaba** [cornerstonejs/cornerstone3D-beta#576]
Now we want to segment one pixel using segmentationTools, but it's hard to locate the boundary of one pixel. It seems cornerstone3D has performed gaussian smooth operation. Do you have any idea how to display the origianl image before smoothing operation like this.
![image](https://user-images.githubusercontent.com/17982206/234162072-3f58ced9-f848-4fba-8b84-30427196743e.png)

**Comment by sedghi** [comment]
You can use `setProperties` and choose interpolation to be nearest neighbor

**Comment by zhoualibaba** [comment]
Thanks for your reply.
