### ISSUE TITLE
Bug: The previous image for the first imageId does not match the image

### ISSUE THREAD

**Issue by jlopes90** [cornerstonejs/cornerstone3D-beta#591]
How to find error:
Scroll down once and then scroll up once.
What happens:
The first image doesn't change so it stayed in the second image.

I already tested the ohif demo also error.
https://v3-demo.ohif.org/viewer?StudyInstanceUIDs=1.3.6.1.4.1.32722.99.99.270210390546167243599316128636641521105

**Comment by sedghi** [comment]
hmm, interesting, yeah I can reproduce it
