### ISSUE TITLE
Default patient orientation

### ISSUE THREAD

**Issue by simonalo** [cornerstonejs/cornerstone3D-beta#597]
Hello, 
Is there a way to display the viewport with a default patient  orientation ? For example, in axial orientation, I would like to display the image with the markers A at the bottom and R at the right.

**Comment by kubanm3** [comment]
Here is implementation of markers in OHIF viewer. It's in react.
https://github.com/OHIF/Viewers/blob/v3-stable/extensions/cornerstone/src/Viewport/Overlays/ViewportOrientationMarkers.tsx

**Comment by simonalo** [comment]
Thank you, I found what I was looking for. My problem was not about the markers but how to set a specific orientation to the viewport. I found that I can specify the orientation by giving it to the viewport ('axial' or 'sagittal' for example). But it does not work for the StackViewport. I made some changes to handle this case.
