### ISSUE TITLE
[Segmentation] The segmentation becomes stretched in 3D volume Rendering

### ISSUE THREAD

**Issue by iamiota** [cornerstonejs/cornerstone3D-beta#601]
In rendering segmentation within a 3D volume, certain perspectives may cause the segmentation to become stretched.

demo: https://github.com/iamiota/segmentation-stretch

Parallel view
<img width="394" alt="image" src="https://user-images.githubusercontent.com/7531576/236726037-e74a3a75-2ee1-40df-a52b-8a0ed7fd01f2.png">

Oblique view
<img width="472" alt="image" src="https://user-images.githubusercontent.com/7531576/236726020-6c7d10c0-aae2-4ca4-adb2-16c20d977534.png">

https://user-images.githubusercontent.com/7531576/236726439-6efb6187-4d3b-41b2-9901-91ba520691d4.mp4

**Comment by sedghi** [comment]
It is not a shift, it seems like the SEG is not volume rendered as I see. can you disable the outline for SEG?

**Comment by iamiota** [comment]
After disabling the outline render, the segmentation display is normal, thank you!

https://github.com/cornerstonejs/cornerstone3D-beta/assets/7531576/b902b377-b5fb-4ae0-ab25-5ccc17c78433

**Comment by sedghi** [comment]
Yeah we have a custom rendering pipeline for rendering outline which only work for non-3d as of now
