### ISSUE TITLE
Will there be a conflict when cornerstone and cornerstone3d beta are used at the same time?

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#69]
Will there be a conflict when cornerstone and cornerstone3d beta are used at the same time?

**Comment by abluobo** [comment]
Thank you for your reply！ @sedghi 
Cornerstone3d provides some advanced functions that brighten my eyes, but some functions still need to be realized by cornerstone, which is why I ask this question.

**Comment by sedghi** [comment]
@abluobo Glad to hear that. 
We always welcome the comments from the community, and would like to hear about the features you are using now in `cornerstone` but is missing in `cornerstone3D`. This certainly helps us for the feature parity which we will do in the future

**Comment by abluobo** [comment]
Okay, I'll do that.
