### ISSUE TITLE
[Vite] Uncaught TypeError: RequestPoolManager is not a constructor     at imageRetrievalPoolManager.ts:11:35

### ISSUE THREAD

**Issue by richardc-zapsurgical** [cornerstonejs/cornerstone3D-beta#92]
Unfortunately, that's the only piece of information that I get. Using a debugger, I have linked it to simply importing `@cornerstonejs/core`.

![image](https://user-images.githubusercontent.com/104937583/166822052-5f770800-7883-4c58-ad41-f4ef1a31037a.png)

My current setup is as follows:
- Windows 10
- Vite: 2.7.2
- React: 17.0.2
- Typescript: 4.4.4
- Node: 16.13.2

Cornerstone-Related Library Versions:
```
- @cornerstonejs/calculate-suv: 1.0.2
- @cornerstonejs/core: 0.7.0
- @cornerstonejs/streaming-image-volume-loader: 0.2.24
- @cornerstonejs/tools: 0.10.1
- @kitware/vtk.js 24.0.0
- detect-gpu 4.0.20
- gl-matrix 3.4.3
```

Notable Actions:
Similar to #80 , I had issues with peer dependencies and used --force when installing `@cornerstonejs/tools` and `@cornerstonejs/streaming-image-volume-loader`.

This may be related: #64

**Comment by richardc-zapsurgical** [comment]
Closing issue since it seems to have been a Vite issue. Specifically, Vite uses ESbuild in development and then ESbuild was reordering the class `RequestPoolManager` definition and converting it to a variable which broke hoisting.

Excluding `@cornerstone/core` and then using `vite-plugin-commonjs` helped fix it for now.

**Comment by richardc-zapsurgical** [comment]
Ended up not using cornerstone for performance reasons, so I'm just browsing through old code to see what might work.

Try this:
```js
{
  define: {
    global: {}
  },

  build: {
    minify: false,
  },
  plugins: [
    vue(),
    viteCommonjs(),
  ],
  optimizeDeps: {
    exclude: ['@cornerstonejs/core']
  }
}
```

**Comment by LSanchez94** [comment]
Hello, I'm having the same error, I already applied this changes, but now I'm getting and error with other dependencies that cornerstone use like globalThis, how did you solve that? because I'm unabled or running the project.

**Comment by mxj009** [comment]
the above is not a standard solution, but also depends on the framework support

**Comment by acegank** [comment]
@LSanchez94 me too? what do you solve this?

**Comment by Debaray** [comment]
@LSanchez94 me also facing the same error. are you solve this or use similar anything?

**Comment by Debaray** [comment]
@richardc-zapsurgical hey I use your mentioned configuration. but now I am getting an error with other dependencies that is cornerstone use globalThis, how did you solve that? I am not found any solution. Please help.
